services:
  backend:
    container_name: synkan-backend
    build:
      context: ./backend/Synkan.API
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=synkan;Username=postgres;Password=1234
      ConnectionStrings__Redis: redis:6379
    ports:
      - "5234:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - synkan
  
  postgres:
    image: postgres:18-alpine
    container_name: synkan-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB must be set}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER must be set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      - synkan
  
  redis:
    image: redis:8-alpine
    container_name: synkan-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - synkan
  
  redis-insight:
    image: redis/redisinsight:3.6
    container_name: synkan-redis-insight
    restart: unless-stopped
    volumes:
      - redis_insight_data:/data
    ports:
      - "5540:5540"
    networks:
      - synkan
  
  prometheus:
    image: prom/prometheus:v3
    container_name: synkan-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - synkan
  
  loki:
    image: grafana/loki:3.7.3
    container_name: synkan-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - synkan
  
  alloy:
    image: grafana/alloy:v1.17.1
    container_name: synkan-alloy
    restart: unless-stopped
    volumes:
      - ./deployment/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    networks:
      - synkan
    depends_on:
      - loki
  
  grafana:
    image: grafana/grafana:13.1.0
    container_name: synkan-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    networks:
      - synkan

volumes:
  postgres_data:
  redis_data:
  redis_insight_data:
  prometheus_data:
  loki_data:
  grafana_data:

networks:
  synkan:
    driver: bridge
